### ISSUE TITLE
Unable to run apt-add-repository on 5.18.0-1parrot1-amd64

### ISSUE THREAD

**Issue by Technoodle** [anbox/anbox-modules#99]
Ive spent a night or two trying to get anbox installed to no success, so I've decided to make an issue post here in order to get direct help, as i cant find any posts about this less than 1-2 years old and outdated. 

When I run apt-add-repository with no arguments it seems to work fine, however when I run the command to actually install the modules, I get this error. Am I being dumb? Ive got no idea whats wrong, or how to fix it.

```
$sudo apt-add-repository ppa:morphis/anbox-support

Traceback (most recent call last):
  File "/usr/bin/apt-add-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 103, in __init__
    self.sourceslist = SourcesList()
  File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 276, in __init__
    self.refresh()
  File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 292, in refresh
    self.matcher.match(source)
  File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 484, in match
    if (re.search(template.match_uri, source.uri) and
  File "/usr/lib/python3.9/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib/python3.9/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.9/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.9/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.9/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.9/sre_parse.py", line 834, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/usr/lib/python3.9/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.9/sre_parse.py", line 834, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/usr/lib/python3.9/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.9/sre_parse.py", line 668, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 2`
```

**Comment by blessedjasonmwanza** [comment]
I have also been experiencing the same issue every time I try to add a repository and I can't seem to find a solution online yet.

For example, [I cannot install PHP 8](https://stackoverflow.com/questions/73826006/parrot-os-unable-to-locate-package-php8-1) due to the same issue

**Comment by SoulInfernoDE** [comment]
Are you sure you are using:
`add-apt-repository`
instead
`apt-add-repository`  ?


..besides that adding this old ppa is not recommended at all any more and debian is not supported at all is what i have read.

**Comment by SLAYER-CODE** [comment]
> También he estado experimentando el mismo problema cada vez que intento agregar un repositorio y parece que todavía no puedo encontrar una solución en línea.
> 
> Por ejemplo, [no puedo instalar PHP 8](https://stackoverflow.com/questions/73826006/parrot-os-unable-to-locate-package-php8-1) debido al mismo problema

I managed to install it through xamp and phpenv

**Comment by Ahtnezev** [comment]
En mi caso que quería instalar PHP 8.1, pude encontrar una solución temporal creando un enlace simbólico del PHP que utiliza XAMPP.

https://stackoverflow.com/questions/75272682/temp-solv-from-unable-to-run-apt-add-repository-on-5-18-0-1parrot1-amd64#new-answer
